### ISSUE TITLE
Copy

### ISSUE THREAD

**Issue by mxstbr** [mstoiber/pgp.asc#2]
I wrote some stuff, stole some stuff from Curtis' PGP Guide (http://curtiswallen.com/pgp), but it's very far from acceptable. Discuss any changes you think are appropriate here! (Missing stuff, stuff that should be deleted, different wording,...)

**Comment by mxstbr** [comment]
**TODO**
- [ ] Rewrite copy according to security concerns mentioned in #18 
- [ ] Add security concerns from #18 somewhere on the page
- [ ] Explain Hall of Fame on the page
